name: form_model
description: "A powerful and flexible form validation package for Flutter applications."
version: 1.0.0
homepage: https://github.com/sukhrob-djumaev/form_model
repository: https://github.com/sukhrob-djumaev/form_model
issue_tracker: https://github.com/sukhrob-djumaev/form_model/issues
topics: [form, bloc, freezed, state-management, validator, internationalization]

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter